##
# Basic
#
site_title: Apretaste
base_url: ~
rewrite_url: ~
timezone: America/New_York

##
# Theme
#
theme: bitsandpieces
theme_url: ~
theme_config:
    widescreen: false
twig_config:
    cache: false
    autoescape: false
    debug: false

##
# Content
#
date_format: %D %T
pages_order_by_meta: author
pages_order_by: alpha
pages_order: asc
content_dir: content
content_ext: .md
content_config:
    extra: true
    breaks: false
    escape: false
    auto_urls: true

##
# Plugins
#
DummyPlugin.enabled: false
